<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class GudangJakartaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $taskgudangjakarta = [
            // Tugas hari Senin
            [
                'title' => 'Pisahkan resi sebelumnya yang belum selesai, packing dengan resi terbaru (Admin Gudang)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Perhatikan resi fisik setelah di print, quantity terpotong / tidak (Admin Gudang)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Seseuaikan jumlah resi fisik setelah di print dengan yang di email / software (Admin Gudang)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Pastikan tida ada scan double / resi double (Admin Gudang)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Saat penyerahan paket, wajib TTD kurir untuk memastikan nomer resi dan jumlah paket yang dibawa (Admin Gudang)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Penyelesaian barang retur info ke kantor (Admin Gudang)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Penyelesaian barang masuk & barang keluar, info ke kantor (Admin Gudang)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Buat surat jalan saat pengambilan barang jika tidak di ambil semuanya (Admin Gudang)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Follow up pekerjaan yang belum ke atasan setiap hari (Kepala Gudang)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Kontrol tidak ada resi yang tertinggal di tempat pengambilan barang (Kepala Gudang)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Sebelum pulang istirahat konfirmasi laporan pekerjaan, (cek resi apa saja yang belum selesai) (Kepala gudang, Wakil & admin)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Jika ada pengiriman yang tidak sempat, tidak terburu, tidak terantar konfirmasi ke atasan (Kepala gudang, Wakil & admin)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Kontrol semua bagian agar berjalan dengan baik & terselesaikan (Kepala gudang, Wakil & admin)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Kontrol tidak ada resi yang tertinggal di tempat pengambilan barang (Kepala gudang, Wakil & admin)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Membungkus pesanan konsumen (Packing)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Pastikan kembali untuk yang akan dipacking, dengan resi, tempat resi sesuai dengan yang dipacking (Packing)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Setelah packing letakkan pada wadah / keranjang per eksposisi / per kurir (Packing)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Merakit produk jika ada waktu luang (Packing)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Cek quantity barang pesanan konsumen dan sesuaikan dengan resi (resi tidak boleh cacat / terpotong) (Checker)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Cek quantity barang masuk (Checker)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Perhatikan benar-benar untuk pesanan dan quuantity barang jangan asal cepat dan siap (Checker)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Melingkari item di quantity jika sesuai (jangan asal) (Checker)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Mengambil produk yang di pesan konsumen (Picker)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Menyusun barang masuk ke gudang (Picker)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Perhatikan quantity pada resi saat pengambilan barang jika quantity resi terpotong / tidak jelas infokan ke admin (Picker)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Perhatikan item barang di resi saat pengambilan barang (Picker)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Mengisi barang kosong / kurang di rak (Picker)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Resi jangan diletakkan sembarangan tempat, saat belum di ambil barangnya (Picker)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],

            // Tugas hari Selasa
            [
                'title' => 'Pisahkan resi sebelumnya yang belum selesai, packing dengan resi terbaru (Admin Gudang)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Perhatikan resi fisik setelah di print, quantity terpotong / tidak (Admin Gudang)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Seseuaikan jumlah resi fisik setelah di print dengan yang di email / software (Admin Gudang)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Pastikan tida ada scan double / resi double (Admin Gudang)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Saat penyerahan paket, wajib TTD kurir untuk memastikan nomer resi dan jumlah paket yang dibawa (Admin Gudang)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Penyelesaian barang retur info ke kantor (Admin Gudang)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Penyelesaian barang masuk & barang keluar, info ke kantor (Admin Gudang)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Buat surat jalan saat pengambilan barang jika tidak di ambil semuanya (Admin Gudang)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Follow up pekerjaan yang belum ke atasan setiap hari (Kepala Gudang)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Kontrol tidak ada resi yang tertinggal di tempat pengambilan barang (Kepala Gudang)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Sebelum pulang istirahat konfirmasi laporan pekerjaan, (cek resi apa saja yang belum selesai) (Kepala gudang, Wakil & admin)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Jika ada pengiriman yang tidak sempat, tidak terburu, tidak terantar konfirmasi ke atasan (Kepala gudang, Wakil & admin)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Kontrol semua bagian agar berjalan dengan baik & terselesaikan (Kepala gudang, Wakil & admin)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Kontrol tidak ada resi yang tertinggal di tempat pengambilan barang (Kepala gudang, Wakil & admin)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Membungkus pesanan konsumen (Packing)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Pastikan kembali untuk yang akan dipacking, dengan resi, tempat resi sesuai dengan yang dipacking (Packing)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Setelah packing letakkan pada wadah / keranjang per eksposisi / per kurir (Packing)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Merakit produk jika ada waktu luang (Packing)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Cek quantity barang pesanan konsumen dan sesuaikan dengan resi (resi tidak boleh cacat / terpotong) (Checker)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Cek quantity barang masuk (Checker)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Perhatikan benar-benar untuk pesanan dan quuantity barang jangan asal cepat dan siap (Checker)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Melingkari item di quantity jika sesuai (jangan asal) (Checker)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Mengambil produk yang di pesan konsumen (Picker)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Menyusun barang masuk ke gudang (Picker)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Perhatikan quantity pada resi saat pengambilan barang jika quantity resi terpotong / tidak jelas infokan ke admin (Picker)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Perhatikan item barang di resi saat pengambilan barang (Picker)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Mengisi barang kosong / kurang di rak (Picker)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Resi jangan diletakkan sembarangan tempat, saat belum di ambil barangnya (Picker)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],

            // Tugas hari Rabu
            [
                'title' => 'Pisahkan resi sebelumnya yang belum selesai, packing dengan resi terbaru (Admin Gudang)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Perhatikan resi fisik setelah di print, quantity terpotong / tidak (Admin Gudang)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Seseuaikan jumlah resi fisik setelah di print dengan yang di email / software (Admin Gudang)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Pastikan tida ada scan double / resi double (Admin Gudang)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Saat penyerahan paket, wajib TTD kurir untuk memastikan nomer resi dan jumlah paket yang dibawa (Admin Gudang)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Penyelesaian barang retur info ke kantor (Admin Gudang)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Penyelesaian barang masuk & barang keluar, info ke kantor (Admin Gudang)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Buat surat jalan saat pengambilan barang jika tidak di ambil semuanya (Admin Gudang)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Follow up pekerjaan yang belum ke atasan setiap hari (Kepala Gudang)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Kontrol tidak ada resi yang tertinggal di tempat pengambilan barang (Kepala Gudang)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Sebelum pulang istirahat konfirmasi laporan pekerjaan, (cek resi apa saja yang belum selesai) (Kepala gudang, Wakil & admin)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Jika ada pengiriman yang tidak sempat, tidak terburu, tidak terantar konfirmasi ke atasan (Kepala gudang, Wakil & admin)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Kontrol semua bagian agar berjalan dengan baik & terselesaikan (Kepala gudang, Wakil & admin)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Kontrol tidak ada resi yang tertinggal di tempat pengambilan barang (Kepala gudang, Wakil & admin)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Membungkus pesanan konsumen (Packing)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Pastikan kembali untuk yang akan dipacking, dengan resi, tempat resi sesuai dengan yang dipacking (Packing)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Setelah packing letakkan pada wadah / keranjang per eksposisi / per kurir (Packing)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Merakit produk jika ada waktu luang (Packing)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Cek quantity barang pesanan konsumen dan sesuaikan dengan resi (resi tidak boleh cacat / terpotong) (Checker)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Cek quantity barang masuk (Checker)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Perhatikan benar-benar untuk pesanan dan quuantity barang jangan asal cepat dan siap (Checker)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Melingkari item di quantity jika sesuai (jangan asal) (Checker)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Mengambil produk yang di pesan konsumen (Picker)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Menyusun barang masuk ke gudang (Picker)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Perhatikan quantity pada resi saat pengambilan barang jika quantity resi terpotong / tidak jelas infokan ke admin (Picker)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Perhatikan item barang di resi saat pengambilan barang (Picker)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Mengisi barang kosong / kurang di rak (Picker)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Resi jangan diletakkan sembarangan tempat, saat belum di ambil barangnya (Picker)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],

            // Tugas hari Kamis
            [
                'title' => 'Pisahkan resi sebelumnya yang belum selesai, packing dengan resi terbaru (Admin Gudang)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Perhatikan resi fisik setelah di print, quantity terpotong / tidak (Admin Gudang)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Seseuaikan jumlah resi fisik setelah di print dengan yang di email / software (Admin Gudang)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Pastikan tida ada scan double / resi double (Admin Gudang)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Saat penyerahan paket, wajib TTD kurir untuk memastikan nomer resi dan jumlah paket yang dibawa (Admin Gudang)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Penyelesaian barang retur info ke kantor (Admin Gudang)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Penyelesaian barang masuk & barang keluar, info ke kantor (Admin Gudang)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Buat surat jalan saat pengambilan barang jika tidak di ambil semuanya (Admin Gudang)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Follow up pekerjaan yang belum ke atasan setiap hari (Kepala Gudang)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Kontrol tidak ada resi yang tertinggal di tempat pengambilan barang (Kepala Gudang)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Sebelum pulang istirahat konfirmasi laporan pekerjaan, (cek resi apa saja yang belum selesai) (Kepala gudang, Wakil & admin)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Jika ada pengiriman yang tidak sempat, tidak terburu, tidak terantar konfirmasi ke atasan (Kepala gudang, Wakil & admin)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Kontrol semua bagian agar berjalan dengan baik & terselesaikan (Kepala gudang, Wakil & admin)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Kontrol tidak ada resi yang tertinggal di tempat pengambilan barang (Kepala gudang, Wakil & admin)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Membungkus pesanan konsumen (Packing)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Pastikan kembali untuk yang akan dipacking, dengan resi, tempat resi sesuai dengan yang dipacking (Packing)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Setelah packing letakkan pada wadah / keranjang per eksposisi / per kurir (Packing)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Merakit produk jika ada waktu luang (Packing)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Cek quantity barang pesanan konsumen dan sesuaikan dengan resi (resi tidak boleh cacat / terpotong) (Checker)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Cek quantity barang masuk (Checker)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Perhatikan benar-benar untuk pesanan dan quuantity barang jangan asal cepat dan siap (Checker)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Melingkari item di quantity jika sesuai (jangan asal) (Checker)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Mengambil produk yang di pesan konsumen (Picker)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Menyusun barang masuk ke gudang (Picker)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Perhatikan quantity pada resi saat pengambilan barang jika quantity resi terpotong / tidak jelas infokan ke admin (Picker)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Perhatikan item barang di resi saat pengambilan barang (Picker)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Mengisi barang kosong / kurang di rak (Picker)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Resi jangan diletakkan sembarangan tempat, saat belum di ambil barangnya (Picker)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],

            // Tugas hari Jumat
            [
                'title' => 'Pisahkan resi sebelumnya yang belum selesai, packing dengan resi terbaru (Admin Gudang)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Perhatikan resi fisik setelah di print, quantity terpotong / tidak (Admin Gudang)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Seseuaikan jumlah resi fisik setelah di print dengan yang di email / software (Admin Gudang)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Pastikan tida ada scan double / resi double (Admin Gudang)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Saat penyerahan paket, wajib TTD kurir untuk memastikan nomer resi dan jumlah paket yang dibawa (Admin Gudang)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Penyelesaian barang retur info ke kantor (Admin Gudang)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Penyelesaian barang masuk & barang keluar, info ke kantor (Admin Gudang)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Buat surat jalan saat pengambilan barang jika tidak di ambil semuanya (Admin Gudang)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Follow up pekerjaan yang belum ke atasan setiap hari (Kepala Gudang)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Kontrol tidak ada resi yang tertinggal di tempat pengambilan barang (Kepala Gudang)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Sebelum pulang istirahat konfirmasi laporan pekerjaan, (cek resi apa saja yang belum selesai) (Kepala gudang, Wakil & admin)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Jika ada pengiriman yang tidak sempat, tidak terburu, tidak terantar konfirmasi ke atasan (Kepala gudang, Wakil & admin)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Kontrol semua bagian agar berjalan dengan baik & terselesaikan (Kepala gudang, Wakil & admin)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Kontrol tidak ada resi yang tertinggal di tempat pengambilan barang (Kepala gudang, Wakil & admin)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Membungkus pesanan konsumen (Packing)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Pastikan kembali untuk yang akan dipacking, dengan resi, tempat resi sesuai dengan yang dipacking (Packing)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Setelah packing letakkan pada wadah / keranjang per eksposisi / per kurir (Packing)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Merakit produk jika ada waktu luang (Packing)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Cek quantity barang pesanan konsumen dan sesuaikan dengan resi (resi tidak boleh cacat / terpotong) (Checker)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Cek quantity barang masuk (Checker)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Perhatikan benar-benar untuk pesanan dan quuantity barang jangan asal cepat dan siap (Checker)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Melingkari item di quantity jika sesuai (jangan asal) (Checker)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Mengambil produk yang di pesan konsumen (Picker)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Menyusun barang masuk ke gudang (Picker)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Perhatikan quantity pada resi saat pengambilan barang jika quantity resi terpotong / tidak jelas infokan ke admin (Picker)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Perhatikan item barang di resi saat pengambilan barang (Picker)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Mengisi barang kosong / kurang di rak (Picker)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Resi jangan diletakkan sembarangan tempat, saat belum di ambil barangnya (Picker)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],

            // Tugas hari Sabtu
            [
                'title' => 'Pisahkan resi sebelumnya yang belum selesai, packing dengan resi terbaru (Admin Gudang)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Perhatikan resi fisik setelah di print, quantity terpotong / tidak (Admin Gudang)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Seseuaikan jumlah resi fisik setelah di print dengan yang di email / software (Admin Gudang)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Pastikan tida ada scan double / resi double (Admin Gudang)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Saat penyerahan paket, wajib TTD kurir untuk memastikan nomer resi dan jumlah paket yang dibawa (Admin Gudang)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Penyelesaian barang retur info ke kantor (Admin Gudang)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Penyelesaian barang masuk & barang keluar, info ke kantor (Admin Gudang)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Buat surat jalan saat pengambilan barang jika tidak di ambil semuanya (Admin Gudang)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Follow up pekerjaan yang belum ke atasan setiap hari (Kepala Gudang)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Kontrol tidak ada resi yang tertinggal di tempat pengambilan barang (Kepala Gudang)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Sebelum pulang istirahat konfirmasi laporan pekerjaan, (cek resi apa saja yang belum selesai) (Kepala gudang, Wakil & admin)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Jika ada pengiriman yang tidak sempat, tidak terburu, tidak terantar konfirmasi ke atasan (Kepala gudang, Wakil & admin)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Kontrol semua bagian agar berjalan dengan baik & terselesaikan (Kepala gudang, Wakil & admin)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Kontrol tidak ada resi yang tertinggal di tempat pengambilan barang (Kepala gudang, Wakil & admin)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Membungkus pesanan konsumen (Packing)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Pastikan kembali untuk yang akan dipacking, dengan resi, tempat resi sesuai dengan yang dipacking (Packing)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Setelah packing letakkan pada wadah / keranjang per eksposisi / per kurir (Packing)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Merakit produk jika ada waktu luang (Packing)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Cek quantity barang pesanan konsumen dan sesuaikan dengan resi (resi tidak boleh cacat / terpotong) (Checker)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Cek quantity barang masuk (Checker)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Perhatikan benar-benar untuk pesanan dan quuantity barang jangan asal cepat dan siap (Checker)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Melingkari item di quantity jika sesuai (jangan asal) (Checker)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Mengambil produk yang di pesan konsumen (Picker)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Menyusun barang masuk ke gudang (Picker)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Perhatikan quantity pada resi saat pengambilan barang jika quantity resi terpotong / tidak jelas infokan ke admin (Picker)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Perhatikan item barang di resi saat pengambilan barang (Picker)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Mengisi barang kosong / kurang di rak (Picker)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
            [
                'title' => 'Resi jangan diletakkan sembarangan tempat, saat belum di ambil barangnya (Picker)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Jakarta',
            ],
        ];
    }
}
