<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TaskAdminMarketingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $taskadminmarketing = [

            // Tugas hari senin
            [
                'title' => 'Cek LPSE',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek yang harus di followup di buku / yang belum ada penyelesaian & wajib dicatat setiap penyampaian tugas maupun bukan',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek follow up penawaran ke konsumen & kirim laporan setiap sore',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Pencatatan barang permintaan ke konsumen yang kosong / barang baru belum datang & sebagainya, berika estimasi waktu tersedia kembali',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek setiap komunikasi yang belum terselesaikan kurang lebih 4 jam',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Share barang masuk / info & upload produk baru (jika ada)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Naikkan produk shopee: pagi-siang-sore',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Mencari konsumen baru di Shopee, Tokopedia, Bukalapak, Lazada, Facebook (jika ada waktu luang cari konsumen di konsumen lapak lain)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek ulasan negative konsumen (wajib dibalas)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek orderan batal / belum terbayar di Shopee, dll',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek barang kosong / arsip di marketplace (wajib ditambah) & ditambahkan produk baru jika ada barang baru',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek harga & cek fisik dengan komputer orderan offline',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Info barang kosong di bagian pembelian',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek pengajuan / pengembalian / pembatalan yang baru dan yang sedang dalam proses (Shopee, Lazada, TOkopedia, & Bukalapak',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Fokus penjualan benih yang mendekati expired',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Komunikasi penawaran dimulai dari grup 3, panah merah, alat, maraca pes, dll',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Info harga turun & naik via chat / telp & tanyakan minta order',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek campaign tiap hari (ikuti)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Barang kosong tetap dicatat (untuk arsip jika datang bisa dikabarkan mengantisipasi lupa)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Barang baru / kosong notanya yang merah di minta isi kapan ready / di order selanjutnya di info ke konsumen estimasi ready',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Nota harga barang di sobek (meminalisir konsumen beli ke yang lain)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Kontrol buku catatan (bawahan) setiap hari',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Kontrol centang satu persatu yang sudah selesai dikerjakan (beri centang)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Kontrol centang keseluruhan tugas wajib yang sudah selesai dikerjakan (beri centang)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Jika sudah 3 hari pindah ke halaman baru',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Kontrol isi tanggal pada halaman atas',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],


            // Tugas hari Selasa
            [
                'title' => 'Cek LPSE',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek yang harus di followup di buku / yang belum ada penyelesaian',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek follow up penawaran ke konsumen & kirim laporan setiap sore',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala atau apa yang belum terselesaikan',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Pencatatan barang permintaan ke konsumen yang kosong / barang baru belum datang & sebagainya, berika estimasi waktu tersedia kembali',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek setiap komunikasi yang belum terselesaikan kurang lebih jam 4',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Share barang masuk / info & upload produk baru (jika ada)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Naikkan produk Shopee, Tokopedia, Lazada, Bukalapak, Facebook (jika ada waktu luang cari konsumen di comment lapak lain',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek ulasan negative konsumen (wajib dibalas)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek orderan batal / belum terbayar di Shopee, dll',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek barang kosong / arsip di marketplace (wajib ditambah) & ditambahkan produk baru jika ada barang baru',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek harga & cek fisik dengan komputer orderan offline',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Info barang kosong di bagian pembelian',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek pengajuan / pengembalian / pembatalan yang baru dan yang sedang dalam proses (Shopee, Lazada, TOkopedia, & Bukalapak',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Fokus penjualan benih yang mendekati expired',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Komunikasi penawaran dimulai dari grup, panah merah, alat, maraca pes, dll',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Info harga turun & naik via chat / telp & tanyakan minta order',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek campaign tiap hari (ikuti)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Barang kosong tetap dicatat (untuk arsip jika datang bisa dikabarkan mengantisipasi lupa)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Barang baru / kosong notanya yang merah di minta isi kapan ready / di order selanjutnya di info ke konsumen estimasi ready',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Nota harga barang di sobek (meminalisir konsumen beli ke yang lain)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Kontrol buku catatan (bawahan) setiap hari',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Kontrol centang satu persatu yang sudah selesai dikerjakan (beri centang)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Kontrol centang keseluruhan tugas wajib yang sudah selesai dikerjakan (beri centang)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Jika sudah 3 hari pindah ke halaman baru',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Isi tanggal pada halaman atas',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],

            // Tugas hari Rabu
            [
                'title' => 'Cek LPSE',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek yang harus di followup di buku / yang belum ada penyelesaian',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek follow up penawaran ke konsumen & kirim laporan setiap sore',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala atau apa yang belum terselesaikan',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Pencatatan barang permintaan ke konsumen yang kosong / barang baru belum datang & sebagainya, berika estimasi waktu tersedia kembali',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek setiap komunikasi yang belum terselesaikan kurang lebih jam 4',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Share barang masuk / info & upload produk baru (jika ada)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Naikkan produk Shopee, Tokopedia, Lazada, Bukalapak, Facebook (jika ada waktu luang cari konsumen di comment lapak lain',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek ulasan negative konsumen (wajib dibalas)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek orderan batal / belum terbayar di Shopee, dll',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek pengajuan / pengembalian / pembatalan yang baru dan yang sedang dalam proses (Shopee, Lazada, TOkopedia, & Bukalapak',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Fokus penjualan benih yang mendekati expired',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Info harga turun & naik via chat / telp & tanyakan minta order',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek campaign tiap hari (ikuti)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Barang kosong tetap dicatat (untuk arsip jika datang bisa dikabarkan mengantisipasi lupa)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Barang baru / kosong notanya yang merah di minta isi kapan ready / di order selanjutnya di info ke konsumen estimasi ready',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Nota harga barang di sobek (meminalisir konsumen beli ke yang lain)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Pomp manual 13.8L konsumen',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Zul kelapangan control buku catatan bawahan',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Kontrol buku catatan (bawahan) setiap hari',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Kontrol centang satu persatu yang sudah selesai dikerjakan (beri centang)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Kontrol centang keseluruhan tugas wajib yang sudah selesai dikerjakan (beri centang)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Jika sudah 3 hari pindah ke halaman baru',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Isi tanggal pada halaman atas',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],

            // Tugas hari Kamis
            [
                'title' => 'Cek LPSE',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek yang harus di followup di buku / yang belum ada penyelesaian',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek follow up penawaran ke konsumen & kirim laporan setiap sore',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala atau apa yang belum terselesaikan',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Pencatatan barang permintaan ke konsumen yang kosong / barang baru belum datang & sebagainya, berika estimasi waktu tersedia kembali',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek setiap komunikasi yang belum terselesaikan kurang lebih jam 4',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Share barang masuk / info & upload produk baru (jika ada)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Naikkan produk Shopee (pagi-siang-sore) cek saldo iklan',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Mencari konsumen baru di Shopee, Tokopedia, Lazada, Bukalapak, Facebook (jika ada waktu luang)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek ulasan negative konsumen (wajib dibalas)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek barang kosong / arsip di marketplace (wajib ditambah) tambahkan produk baru jika sudah ada barang baru',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek pengajuan / pengembalian / pembatalan yang baru dan yang sedang dalam proses (Shopee, Lazada, TOkopedia, & Bukalapak',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Fokus penjualan benih yang mendekati expired',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Info harga turun & naik via chat / telp & tanyakan minta order',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek fisik harga dan computer, jika barang kosong alihkan / tawarkan barang lain',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek campaign tiap hari (ikuti)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Barang kosong tetap dicatat (untuk arsip jika datang bisa dikabarkan mengantisipasi lupa)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Barang baru / kosong notanya yang merah di minta isi kapan ready / di order selanjutnya di info ke konsumen estimasi ready',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Nota harga barang di sobek (meminalisir konsumen beli ke yang lain)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Kontrol buku catatan (bawahan) setiap hari',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Kontrol centang satu persatu yang sudah selesai dikerjakan (beri centang)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Kontrol centang keseluruhan tugas wajib yang sudah selesai dikerjakan (beri centang)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Jika sudah 3 hari pindah ke halaman baru',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Isi tanggal pada halaman atas',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],


            // Tugas hari jumat
            [
                'title' => 'Cek LPSE',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek yang harus di followup di buku / yang belum ada penyelesaian',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek follow up penawaran ke konsumen & kirim laporan setiap sore',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala atau apa yang belum terselesaikan',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Pencatatan barang permintaan ke konsumen yang kosong / barang baru belum datang & sebagainya, berika estimasi waktu tersedia kembali',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek setiap komunikasi yang belum terselesaikan kurang lebih jam 4',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Share barang masuk / info & upload produk baru (jika ada)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Naikkan produk Shopee (pagi-siang-sore) cek saldo iklan',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Mencari konsumen baru di Shopee, Tokopedia, Lazada, Bukalapak, Facebook (jika ada waktu luang)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek ulasan negative konsumen (wajib dibalas)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek barang kosong / arsip di marketplace (wajib ditambah) tambahkan produk baru jika sudah ada barang baru',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek pengajuan / pengembalian / pembatalan yang baru dan yang sedang dalam proses (Shopee, Lazada, TOkopedia, & Bukalapak',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Fokus penjualan benih yang mendekati expired',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek fisik harga dan computer, jika barang kosong alihkan / tawarkan barang lain',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek campaign tiap hari (ikuti)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Barang kosong tetap dicatat (untuk arsip jika datang bisa dikabarkan mengantisipasi lupa)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Nota harga barang di sobek (meminalisir konsumen beli ke yang lain)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Kontrol buku catatan (bawahan) setiap hari',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Kontrol centang satu persatu yang sudah selesai dikerjakan (beri centang)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Kontrol centang keseluruhan tugas wajib yang sudah selesai dikerjakan (beri centang)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Jika sudah 3 hari pindah ke halaman baru',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Isi tanggal pada halaman atas',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],

            // Tugas hari sabtu
            [
                'title' => 'Cek LPSE',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek yang harus di followup di buku / yang belum ada penyelesaian',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek follow up penawaran ke konsumen & kirim laporan setiap sore',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala atau apa yang belum terselesaikan',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Pencatatan barang permintaan ke konsumen yang kosong / barang baru belum datang & sebagainya, berika estimasi waktu tersedia kembali',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek setiap komunikasi yang belum terselesaikan kurang lebih jam 4',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Share barang masuk / info & upload produk baru (jika ada)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Naikkan produk Shopee (pagi-siang-sore) cek saldo iklan',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Mencari konsumen baru di Shopee, Tokopedia, Lazada, Bukalapak, Facebook (jika ada waktu luang)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek ulasan negative konsumen (wajib dibalas)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek barang kosong / arsip di marketplace (wajib ditambah) tambahkan produk baru jika sudah ada barang baru',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek pengajuan / pengembalian / pembatalan yang baru dan yang sedang dalam proses (Shopee, Lazada, TOkopedia, & Bukalapak',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Fokus penjualan benih yang mendekati expired',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Riset harga, produk, promo, pelayanan marketplace pesaing offline',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek fisik harga dan computer, jika barang kosong alihkan / tawarkan barang lain',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek campaign tiap hari (ikuti)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Barang kosong tetap dicatat (untuk arsip jika datang bisa dikabarkan mengantisipasi lupa)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Barang baru / kosong nta merah di minta isi kapan ready / order ',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Nota harga barang di sobek (meminalisir konsumen beli ke yang lain)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Zul kelapangan',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Kontrol buku catatan (bawahan) setiap hari',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Kontrol centang satu persatu yang sudah selesai dikerjakan (beri centang)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Kontrol centang keseluruhan tugas wajib yang sudah selesai dikerjakan (beri centang)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Jika sudah 3 hari pindah ke halaman baru',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Isi tanggal pada halaman atas',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
            [
                'title' => 'Cek harga kewajaran, harga online )',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Admin Marketing',
            ],
        ];

        // Insert the tasks into the database
        DB::table('tasks')->insert($taskadminmarketing);
    }
}
