<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TaskGudangBintanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $taskgudangbintan = [
            // Tugas untuk hari senin
            [
                'title' => 'Cek pengantaran yang belum selesai (pagi / hari sebelumnya)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Produksi atau pengemasan barang',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Mempersiapkan barang orderan',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek tugas (pertanggal)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Follow up jadwal kapal',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Kunci Gudang (sore)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Kebersihan dan kerapian gudang',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek barang sampai pulau (kapan sampai)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek keadaan kendaraan motor-pickup-lori-engkel-froklip radiator & oli (takutnya berkurang)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cuci bak / kendaraan saat selesai antar barang (jika kotor)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Tulis koli di surat jalan & kemasaan packing (dibuat nama pelanggannya)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek yang harus di follow up dibuku / yg belum ada penyelesaian & wajib dicatat setiap penyampaian tugas maupun bukan',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala apa yang belum terselesaikan & follow up tugas yang tidak terselesaikan ke atasan (pagi-siang-sore)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],

            // Tugas hari selasa
            [
                'title' => 'Cek pengantaran yang belum selesai (pagi / hari sebelumnya)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Produksi atau pengemasan barang',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Mempersiapkan barang orderan',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek tugas (pertanggal)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Follow up jadwal kapal',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Kunci Gudang (sore)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Kebersihan dan kerapian gudang',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek barang sampai pulau (kapan sampai)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek keadaan kendaraan motor-pickup-lori-engkel-froklip radiator & oli (takutnya berkurang)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Tulis koli di surat jalan & kemasaan packing (dibuat nama pelanggannya)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek yang harus di follow up dibuku / yg belum ada penyelesaian & wajib dicatat setiap penyampaian tugas maupun bukan',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala apa yang belum terselesaikan & follow up tugas yang tidak terselesaikan ke atasan (pagi-siang-sore)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],

            // Tugas hari Rabu
            [
                'title' => 'Cek pengantaran yang belum selesai (pagi / hari sebelumnya)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Produksi atau pengemasan barang',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Mempersiapkan barang orderan',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek tugas (pertanggal)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Follow up jadwal kapal',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Kunci Gudang (sore)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Kebersihan dan kerapian gudang',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek barang sampai pulau (kapan sampai)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek keadaan kendaraan motor-pickup-lori-engkel-froklip radiator & oli (takutnya berkurang)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Tulis koli di surat jalan & kemasaan packing (dibuat nama pelanggannya)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek yang harus di follow up dibuku / yg belum ada penyelesaian & wajib dicatat setiap penyampaian tugas maupun bukan',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala apa yang belum terselesaikan & follow up tugas yang tidak terselesaikan ke atasan (pagi-siang-sore)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],

            // Tugas hari Kamis
            [
                'title' => 'Cek pengantaran yang belum selesai (pagi / hari sebelumnya)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Produksi atau pengemasan barang',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Mempersiapkan barang orderan',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek tugas (pertanggal)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Follow up jadwal kapal',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Kunci Gudang (sore)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Kebersihan dan kerapian gudang',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek barang sampai pulau (kapan sampai)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek keadaan kendaraan motor-pickup-lori-engkel-froklip radiator & oli (takutnya berkurang)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Tulis koli di surat jalan & kemasaan packing (dibuat nama pelanggannya)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek yang harus di follow up dibuku / yg belum ada penyelesaian & wajib dicatat setiap penyampaian tugas maupun bukan',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala apa yang belum terselesaikan & follow up tugas yang tidak terselesaikan ke atasan (pagi-siang-sore)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],

            // Tugas hari jumat
            [
                'title' => 'Cek pengantaran yang belum selesai (pagi / hari sebelumnya)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Produksi atau pengemasan barang',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Mempersiapkan barang orderan',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek tugas (pertanggal)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Follow up jadwal kapal',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Kunci Gudang (sore)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Kebersihan dan kerapian gudang',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek barang sampai pulau (kapan sampai)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek keadaan kendaraan motor-pickup-lori-engkel-froklip radiator & oli (takutnya berkurang)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Tulis koli di surat jalan & kemasaan packing (dibuat nama pelanggannya)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek yang harus di follow up dibuku / yg belum ada penyelesaian & wajib dicatat setiap penyampaian tugas maupun bukan',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala apa yang belum terselesaikan & follow up tugas yang tidak terselesaikan ke atasan (pagi-siang-sore)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],

            // Tugas hari sabtu
            [
                'title' => 'Cek pengantaran yang belum selesai (pagi / hari sebelumnya)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Produksi atau pengemasan barang',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Mempersiapkan barang orderan',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek tugas (pertanggal)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Follow up jadwal kapal',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Kunci Gudang (sore)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Kebersihan dan kerapian gudang',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek barang sampai pulau (kapan sampai)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek keadaan kendaraan motor-pickup-lori-engkel-froklip radiator & oli (takutnya berkurang)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Tulis koli di surat jalan & kemasaan packing (dibuat nama pelanggannya)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek yang harus di follow up dibuku / yg belum ada penyelesaian & wajib dicatat setiap penyampaian tugas maupun bukan',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala apa yang belum terselesaikan & follow up tugas yang tidak terselesaikan ke atasan (pagi-siang-sore)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
        ];
    }
}
