<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TaskGudangBintanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $taskgudangbintan = [];

        $taskgudangbintan= [
            // Tugas untuk hari senin
            [
                'title' => 'Cek pengantaran yang belum selesai (pagi / hari sebelumnya)',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Produksi atau pengemasan barang',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Mempersiapkan barang orderan',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Cek tugas (pertanggal)',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Follow up jadwal kapal',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Kunci Gudang (sore)',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Kebersihan dan kerapian gudang',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Cek barang sampai pulau (kapan sampai)',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Cek keadaan kendaraan motor-pickup-lori-engkel-froklip radiator & oli (takutnya berkurang)',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Cuci bak / kendaraan saat selesai antar barang (jika kotor)',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Tulis koli di surat jalan & kemasaan packing (dibuat nama pelanggannya)',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Cek yang harus di follow up dibuku / yg belum ada penyelesaian & wajib dicatat setiap penyampaian tugas maupun bukan',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala apa yang belum terselesaikan & follow up tugas yang tidak terselesaikan ke atasan (pagi-siang-sore)',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],

            // Tugas hari selasa
            [
                'title' => 'Cek pengantaran yang belum selesai (pagi / hari sebelumnya)',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Produksi atau pengemasan barang',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Mempersiapkan barang orderan',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Cek tugas (pertanggal)',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Follow up jadwal kapal',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Kunci Gudang (sore)',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Kebersihan dan kerapian gudang',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Cek barang sampai pulau (kapan sampai)',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Cek keadaan kendaraan motor-pickup-lori-engkel-froklip radiator & oli (takutnya berkurang)',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Tulis koli di surat jalan & kemasaan packing (dibuat nama pelanggannya)',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Cek yang harus di follow up dibuku / yg belum ada penyelesaian & wajib dicatat setiap penyampaian tugas maupun bukan',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala apa yang belum terselesaikan & follow up tugas yang tidak terselesaikan ke atasan (pagi-siang-sore)',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],

            // Tugas hari Rabu
            [
                'title' => 'Cek pengantaran yang belum selesai (pagi / hari sebelumnya)',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Produksi atau pengemasan barang',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Mempersiapkan barang orderan',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Cek tugas (pertanggal)',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Follow up jadwal kapal',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Kunci Gudang (sore)',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Kebersihan dan kerapian gudang',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Cek barang sampai pulau (kapan sampai)',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Cek keadaan kendaraan motor-pickup-lori-engkel-froklip radiator & oli (takutnya berkurang)',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Tulis koli di surat jalan & kemasaan packing (dibuat nama pelanggannya)',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Cek yang harus di follow up dibuku / yg belum ada penyelesaian & wajib dicatat setiap penyampaian tugas maupun bukan',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala apa yang belum terselesaikan & follow up tugas yang tidak terselesaikan ke atasan (pagi-siang-sore)',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],

            // Tugas hari Kamis
            [
                'title' => 'Cek pengantaran yang belum selesai (pagi / hari sebelumnya)',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Produksi atau pengemasan barang',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Mempersiapkan barang orderan',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Cek tugas (pertanggal)',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Follow up jadwal kapal',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Kunci Gudang (sore)',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Kebersihan dan kerapian gudang',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Cek barang sampai pulau (kapan sampai)',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Cek keadaan kendaraan motor-pickup-lori-engkel-froklip radiator & oli (takutnya berkurang)',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Tulis koli di surat jalan & kemasaan packing (dibuat nama pelanggannya)',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Cek yang harus di follow up dibuku / yg belum ada penyelesaian & wajib dicatat setiap penyampaian tugas maupun bukan',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala apa yang belum terselesaikan & follow up tugas yang tidak terselesaikan ke atasan (pagi-siang-sore)',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],

            // Tugas hari jumat
            [
                'title' => 'Cek pengantaran yang belum selesai (pagi / hari sebelumnya)',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Produksi atau pengemasan barang',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Mempersiapkan barang orderan',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Cek tugas (pertanggal)',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Follow up jadwal kapal',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Kunci Gudang (sore)',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Kebersihan dan kerapian gudang',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Cek barang sampai pulau (kapan sampai)',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Cek keadaan kendaraan motor-pickup-lori-engkel-froklip radiator & oli (takutnya berkurang)',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Tulis koli di surat jalan & kemasaan packing (dibuat nama pelanggannya)',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Cek yang harus di follow up dibuku / yg belum ada penyelesaian & wajib dicatat setiap penyampaian tugas maupun bukan',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala apa yang belum terselesaikan & follow up tugas yang tidak terselesaikan ke atasan (pagi-siang-sore)',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],

            // Tugas hari sabtu
            [
                'title' => 'Cek pengantaran yang belum selesai (pagi / hari sebelumnya)',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Produksi atau pengemasan barang',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Mempersiapkan barang orderan',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Cek tugas (pertanggal)',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Follow up jadwal kapal',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Kunci Gudang (sore)',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Kebersihan dan kerapian gudang',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Cek barang sampai pulau (kapan sampai)',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Cek keadaan kendaraan motor-pickup-lori-engkel-froklip radiator & oli (takutnya berkurang)',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Tulis koli di surat jalan & kemasaan packing (dibuat nama pelanggannya)',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Cek yang harus di follow up dibuku / yg belum ada penyelesaian & wajib dicatat setiap penyampaian tugas maupun bukan',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala apa yang belum terselesaikan & follow up tugas yang tidak terselesaikan ke atasan (pagi-siang-sore)',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Gudang Bintan',
            ],
        ];

        // Insert the tasks into the database
        DB::table('tasks')->insert($taskgudangbintan);
    }
}
