<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TaskAdminSaleSeeders extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tasksadminsale = [
            // Tugas untuk hari senin
            [
                'title' => 'Pengecekan buku catatan harian siang dan sore',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Penyelesaian pencatatan yang belum selesai siang dan sore, wajib dicatat setiap penyampaian tugas maupun bukan',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala atau apa yang belum terselesaikan & follow up tugas yang tidak terselesaikan ke atasan, (pagi, siang, sore)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek piutang yang harus ditagih (jatuh tempo)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Foto nota piutang (tagihan via online)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Pisahkan nota  < 5 hari jatuh tempo',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Penagihan piutang dan kontrol',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek olshop yang mau terbatalkan / tidak terproses siang & sore',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Penyelesaian piutang olshop bermasalah dan lebih dari 2 minggu & piutang offline lewat masa tenggang',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Shopee, Tokopedia, Lazada dilaporkan ke atasan jika ada kendala (pengembalian)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek pengembalian Shopee, Lazada, Tokopedia yang baru & dalam proses',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Konfirmasi via telp jika ada perubahan nama item untuk Gudang Jakarta dan Bintan',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Penutupan buku (penerimaan piutang)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Input nota, info barang kosong, persiapan nota invoice pengantaran',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Nota marketplace dikirim kurang lebih jam 11.00',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Buat nota / invoice antar cabang (penjualan)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Untuk admin penjualan SO penjualan di selesaikan di hari ini juga, jika terdapat kendala konfirmasi ke atasan',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Setiap data wajib email (arsip)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Input piutang',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek piutang, sesuaikan fisik invoice piutang dengan komputer',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek & selesaikan min-max pesaan Shopee, Lazada, Tokopedia, jika terdapat kendala lakukan konfirmasi ke atasan (piutang marketplace)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Metting ke MGR piutang tidak selesai / bermasalah (senin pagi) perminggu',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek nota yang sudah di print hari ini, cek saat nota sudah selesai sore/pagi',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Print email masuk hari sebelumnya',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Nota retur marketplace / pengembalian / pembatalan',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Surat jalan offline dan online',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Hapus barang kosong, baran pengembalian online setiap hari (retur)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Setiap permasalahan pengiriman, wajib diinfokan secara tertulis (gudang Jakarta)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Input nota retur offline (cek diskon sebelumnya, input no inv & keterangan retur)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Setiap akan membuka nota retur, harus dengan ACC & ditandatangani oleh atasan (hapus nota salah input, edit salah order dll)',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Import penjualan marketplace ke GF Akuntansi wajib diselesaikan setiap hari',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Setor ke bank Senin-Jumat',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Input pembayaran hutang',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Laporan balance kas',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Untuk kebun sendiri harus ttd di surat jalan kak axia / bang aming',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Biaya untuk iklan Shopee tidak boleh lebih dari 10%, jika lebih kabari langsung ke atasan',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Pengembalian maksimal 20.000, Acc boss pengembalian dana saja tidak perlu pengembalian barang',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek pekerjaan admin Faraco, Bintan & Gudang',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Pindah gudang Batam setiap hari Selasa & Jumat, kecuali urgent',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Jika ada yang TF kurang dari 20.000 dibuat saja diskon Acc Boss 12/06/24',
                'date' => Carbon::now()->next('Monday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            

            // Tugas hari selasa
            [
                'title' => 'Pengecekan buku catatan harian siang dan sore',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Penyelesaian pencatatan yang belum selesai siang dan sore, wajib dicatat setiap penyampaian tugas maupun bukan',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala atau apa yang belum terselesaikan & follow up tugas yang tidak terselesaikan ke atasan, (pagi, siang, sore)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek piutang yang harus ditagih (jatuh tempo)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Foto nota piutang (tagihan via online)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Pisahkan nota < 5 hari jatuh tempo',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Penagihan piutang dan kontrol',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek olshop yang mau terbatalkan / tidak terproses siang & sore',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Penyelesaian piutang olshop bermasalah dan lebih dari 2 minggu & piutang offline lewat masa tenggang',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Shopee, Tokopedia, Lazada dilaporkan ke atasan jika ada kendala (pengembalian)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek pengembalian Shopee, Lazada, Tokopedia yang baru & dalam proses',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Konfirmasi via telp jika ada perubahan nama item untuk Gudang Jakarta dan Bintan',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Penutupan buku (penerimaan piutang)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Input nota, info barang kosong, persiapan nota invoice pengantaran',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Nota marketplace dikirim kurang lebih jam 11.00',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Buat nota / invoice antar cabang (penjualan)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Untuk admin penjualan SO penjualan di selesaikan di hari ini juga, jika terdapat kendala konfirmasi ke atasan',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Setiap data wajib email (arsip)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Input piutang',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek piutang, sesuaikan fisik invoice piutang dengan komputer',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek & selesaikan min-max pesaan Shopee, Lazada, Tokopedia, jika terdapat kendala lakukan konfirmasi ke atasan (piutang marketplace)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Metting ke MGR piutang tidak selesai / bermasalah (senin pagi) perminggu',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek nota yang sudah di print hari ini, cek saat nota sudah selesai sore/pagi',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Print email masuk hari sebelumnya',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Nota retur marketplace / pengembalian / pembatalan',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Surat jalan offline dan online',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Hapus barang kosong, baran pengembalian online setiap hari (retur)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Setiap permasalahan pengiriman, wajib diinfokan secara tertulis (gudang Jakarta)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Input nota retur offline (cek diskon sebelumnya, input no inv & keterangan retur)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Setiap akan membuka nota retur, harus dengan ACC & ditandatangani oleh atasan (hapus nota salah input, edit salah order dll)',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Import penjualan marketplace ke GF Akuntansi wajib diselesaikan setiap hari',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Setor ke bank Senin-Jumat',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Input pembayaran hutang',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Laporan balance kas',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Untuk kebun sendiri harus ttd di surat jalan kak axia / bang aming',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Biaya untuk iklan Shopee tidak boleh lebih dari 10%, jika lebih kabari langsung ke atasan',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Pengembalian maksimal 20.000, Acc boss pengembalian dana saja tidak perlu pengembalian barang',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek pekerjaan admin Faraco, Bintan & Gudang',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Pindah gudang Batam setiap hari Selasa & Jumat, kecuali urgent',
                'date' => Carbon::now()->next('Tuesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],

            // Tugas Hari Rabu
            [
                'title' => 'Pengecekan buku catatan harian siang dan sore',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Penyelesaian pencatatan yang belum selesai siang dan sore, wajib dicatat setiap penyampaian tugas maupun bukan',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala atau apa yang belum terselesaikan & follow up tugas yang tidak terselesaikan ke atasan, (pagi, siang, sore)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek piutang yang harus ditagih (jatuh tempo)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Foto nota piutang (tagihan via online)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Pisahkan nota < 5 hari jatuh tempo',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Penagihan piutang dan kontrol',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek olshop yang mau terbatalkan / tidak terproses siang & sore',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Penyelesaian piutang olshop bermasalah dan lebih dari 2 minggu & piutang offline lewat masa tenggang',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Shopee, Tokopedia, Lazada dilaporkan ke atasan jika ada kendala (pengembalian)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek pengembalian Shopee, Lazada, Tokopedia yang baru & dalam proses',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Konfirmasi via telp jika ada perubahan nama item untuk Gudang Jakarta dan Bintan',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Penutupan buku (penerimaan piutang)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Input nota, info barang kosong, persiapan nota invoice pengantaran',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Nota marketplace dikirim kurang lebih jam 11.00',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Buat nota / invoice antar cabang (penjualan)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Untuk admin penjualan SO penjualan di selesaikan di hari ini juga, jika terdapat kendala konfirmasi ke atasan',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Setiap data wajib email (arsip)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Input piutang',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek piutang, sesuaikan fisik invoice piutang dengan komputer',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek & selesaikan min-max pesaan Shopee, Lazada, Tokopedia, jika terdapat kendala lakukan konfirmasi ke atasan (piutang marketplace)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Metting ke MGR piutang tidak selesai / bermasalah (senin pagi) perminggu',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek nota yang sudah di print hari ini, cek saat nota sudah selesai sore/pagi',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Print email masuk hari sebelumnya',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Nota retur marketplace / pengembalian / pembatalan',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Surat jalan offline dan online',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Hapus barang kosong, baran pengembalian online setiap hari (retur)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Setiap permasalahan pengiriman, wajib diinfokan secara tertulis (gudang Jakarta)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Input nota retur offline (cek diskon sebelumnya, input no inv & keterangan retur)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Setiap akan membuka nota retur, harus dengan ACC & ditandatangani oleh atasan (hapus nota salah input, edit salah order dll)',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Import penjualan marketplace ke GF Akuntansi wajib diselesaikan setiap hari',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Setor ke bank Senin-Jumat',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Input pembayaran hutang',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Laporan balance kas',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Untuk kebun sendiri harus ttd di surat jalan kak axia / bang aming',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Biaya untuk iklan Shopee tidak boleh lebih dari 10%, jika lebih kabari langsung ke atasan',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Pengembalian maksimal 20.000, Acc boss pengembalian dana saja tidak perlu pengembalian barang',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek pekerjaan admin Faraco, Bintan & Gudang',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Pindah gudang Batam setiap hari Selasa & Jumat, kecuali urgent',
                'date' => Carbon::now()->next('Wednesday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],

            // Tugas Hari Kamis
            [
                'title' => 'Pengecekan buku catatan harian siang dan sore',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Penyelesaian pencatatan yang belum selesai siang dan sore, wajib dicatat setiap penyampaian tugas maupun bukan',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala atau apa yang belum terselesaikan & follow up tugas yang tidak terselesaikan ke atasan, (pagi, siang, sore)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek piutang yang harus ditagih (jatuh tempo)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Foto nota piutang (tagihan via online)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Pisahkan nota < 5 hari jatuh tempo',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Penagihan piutang dan kontrol',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek olshop yang mau terbatalkan / tidak terproses siang & sore',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Penyelesaian piutang olshop bermasalah dan lebih dari 2 minggu & piutang offline lewat masa tenggang',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Shopee, Tokopedia, Lazada dilaporkan ke atasan jika ada kendala (pengembalian)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek pengembalian Shopee, Lazada, Tokopedia yang baru & dalam proses',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Konfirmasi via telp jika ada perubahan nama item untuk Gudang Jakarta dan Bintan',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Penutupan buku (penerimaan piutang)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Input nota, info barang kosong, persiapan nota invoice pengantaran',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Nota marketplace dikirim kurang lebih jam 11.00',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Buat nota / invoice antar cabang (penjualan)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Untuk admin penjualan SO penjualan di selesaikan di hari ini juga, jika terdapat kendala konfirmasi ke atasan',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Setiap data wajib email (arsip)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Input piutang',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek piutang, sesuaikan fisik invoice piutang dengan komputer',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek & selesaikan min-max pesaan Shopee, Lazada, Tokopedia, jika terdapat kendala lakukan konfirmasi ke atasan (piutang marketplace)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Metting ke MGR piutang tidak selesai / bermasalah (senin pagi) perminggu',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek nota yang sudah di print hari ini, cek saat nota sudah selesai sore/pagi',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Print emai masuk hari sebelumnya',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Nota retur marketplace / pengembalian / pembatalan',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Surat jalan offline dan online',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Hapus barang kosong, baran pengembalian online setiap hari (retur)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Setiap permasalahan pengiriman, wajib diinfokan secara tertulis (gudang Jakarta)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Input nota retur offline (cek diskon sebelumnya, input no inv & keterangan retur)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Setiap akan membuka nota retur, harus dengan ACC & ditandatangani oleh atasan (hapus nota salah input, edit salah order dll)',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Import penjualan marketplace ke GF Akuntansi wajib diselesaikan setiap hari',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Setor ke bank Senin-Jumat',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Input pembayaran hutang',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Laporan balance kas',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Untuk kebun sendiri harus ttd di surat jalan kak axia / bang aming',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Biaya untuk iklan Shopee tidak boleh lebih dari 10%, jika lebih kabari langsung ke atasan',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Pengembalian maksimal 20.000, Acc boss pengembalian dana saja tidak perlu pengembalian barang',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek pekerjaan admin Faraco, Bintan & Gudang',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Pindah gudang Batam setiap hari Selasa & Jumat, kecuali urgent',
                'date' => Carbon::now()->next('Thursday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],

            // Tugas hari Jumat
            [
                'title' => 'Pengecekan buku catatan harian siang dan sore',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Penyelesaian pencatatan yang belum selesai siang dan sore, wajib dicatat setiap penyampaian tugas maupun bukan',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala atau apa yang belum terselesaikan & follow up tugas yang tidak terselesaikan ke atasan, (pagi, siang, sore)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek piutang yang harus ditagih (jatuh tempo)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Foto nota piutang (tagihan via online)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Pisahkan nota < 5 hari jatuh tempo',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Penagihan piutang dan kontrol',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek olshop yang mau terbatalkan / tidak terproses siang & sore',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Penyelesaian piutang olshop bermasalah dan lebih dari 2 minggu & piutang offline lewat masa tenggang',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Shopee, Tokopedia, Lazada dilaporkan ke atasan jika ada kendala (pengembalian)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek pengembalian Shopee, Lazada, Tokopedia yang baru & dalam proses',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Konfirmasi via telp jika ada perubahan nama item untuk Gudang Jakarta dan Bintan',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Penutupan buku (penerimaan piutang)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Input nota, info barang kosong, persiapan nota invoice pengantaran',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Nota marketplace dikirim kurang lebih jam 11.00',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Buat nota / invoice antar cabang (penjualan)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Untuk admin penjualan SO penjualan di selesaikan di hari ini juga, jika terdapat kendala konfirmasi ke atasan',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Setiap data wajib email (arsip)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Input piutang',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek piutang, sesuaikan fisik invoice piutang dengan komputer',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek & selesaikan min-max pesaan Shopee, Lazada, Tokopedia, jika terdapat kendala lakukan konfirmasi ke atasan (piutang marketplace)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Metting ke MGR piutang tidak selesai / bermasalah (senin pagi) perminggu',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek nota yang sudah di print hari ini, cek saat nota sudah selesai sore/pagi',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Print emai masuk hari sebelumnya',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Nota retur marketplace / pengembalian / pembatalan',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Surat jalan offline dan online',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Hapus barang kosong, baran pengembalian online setiap hari (retur)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Setiap permasalahan pengiriman, wajib diinfokan secara tertulis (gudang Jakarta)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Input nota retur offline (cek diskon sebelumnya, input no inv & keterangan retur)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Setiap akan membuka nota retur, harus dengan ACC & ditandatangani oleh atasan (hapus nota salah input, edit salah order dll)',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Import penjualan marketplace ke GF Akuntansi wajib diselesaikan setiap hari',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Setor ke bank Senin-Jumat',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Input pembayaran hutang',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Laporan balance kas',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Untuk kebun sendiri harus ttd di surat jalan kak axia / bang aming',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Biaya untuk iklan Shopee tidak boleh lebih dari 10%, jika lebih kabari langsung ke atasan',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Pengembalian maksimal 20.000, Acc boss pengembalian dana saja tidak perlu pengembalian barang',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek pekerjaan admin Faraco, Bintan & Gudang',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Pindah gudang Batam setiap hari Selasa & Jumat, kecuali urgent',
                'date' => Carbon::now()->next('Friday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],

            // Tugas hari Sabtu
            [
                'title' => 'Pengecekan buku catatan harian siang dan sore',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Penyelesaian pencatatan yang belum selesai siang dan sore, wajib dicatat setiap penyampaian tugas maupun bukan',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala atau apa yang belum terselesaikan & follow up tugas yang tidak terselesaikan ke atasan, (pagi, siang, sore)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek piutang yang harus ditagih (jatuh tempo)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Foto nota piutang (tagihan via online)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Pisahkan nota < 5 hari jatuh tempo',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Penagihan piutang dan kontrol',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek olshop yang mau terbatalkan / tidak terproses siang & sore',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Penyelesaian piutang olshop bermasalah dan lebih dari 2 minggu & piutang offline lewat masa tenggang',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Shopee, Tokopedia, Lazada dilaporkan ke atasan jika ada kendala (pengembalian)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek pengembalian Shopee, Lazada, Tokopedia yang baru & dalam proses',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Konfirmasi via telp jika ada perubahan nama item untuk Gudang Jakarta dan Bintan',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Penutupan buku (penerimaan piutang)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Input nota, info barang kosong, persiapan nota invoice pengantaran',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Nota marketplace dikirim kurang lebih jam 11.00',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Buat nota / invoice antar cabang (penjualan)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Untuk admin penjualan SO penjualan di selesaikan di hari ini juga, jika terdapat kendala konfirmasi ke atasan',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Setiap data wajib email (arsip)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Input piutang',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek piutang, sesuaikan fisik invoice piutang dengan komputer',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek & selesaikan min-max pesaan Shopee, Lazada, Tokopedia, jika terdapat kendala lakukan konfirmasi ke atasan (piutang marketplace)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Metting ke MGR piutang tidak selesai / bermasalah (senin pagi) perminggu',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek nota yang sudah di print hari ini, cek saat nota sudah selesai sore/pagi',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Print emai masuk hari sebelumnya',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Nota retur marketplace / pengembalian / pembatalan',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Surat jalan offline dan online',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Hapus barang kosong, baran pengembalian online setiap hari (retur)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Setiap permasalahan pengiriman, wajib diinfokan secara tertulis (gudang Jakarta)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Input nota retur offline (cek diskon sebelumnya, input no inv & keterangan retur)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Setiap akan membuka nota retur, harus dengan ACC & ditandatangani oleh atasan (hapus nota salah input, edit salah order dll)',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Import penjualan marketplace ke GF Akuntansi wajib diselesaikan setiap hari',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Setor ke bank Senin-Jumat',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Input pembayaran hutang',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Laporan balance kas',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Untuk kebun sendiri harus ttd di surat jalan kak axia / bang aming',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Biaya untuk iklan Shopee tidak boleh lebih dari 10%, jika lebih kabari langsung ke atasan',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Pengembalian maksimal 20.000, Acc boss pengembalian dana saja tidak perlu pengembalian barang',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Cek pekerjaan admin Faraco, Bintan & Gudang',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
            [
                'title' => 'Pindah gudang Batam setiap hari Selasa & Jumat, kecuali urgent',
                'date' => Carbon::now()->next('Saturday')->format('Y-m-d'),
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
            ],
        ];
    }
}
