<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TaskManajemenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tasks = [];
        $tasks = [
            // Tugas untuk hari senin
            [
                'title' => 'Lowongan Kerja',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Penyelesaian catatan pertanyaan setiap bagian kerja & kontrol buku masing-masing',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Kontrol tugas harian dan pertanggal setiap bagian',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Cek penyelesaian tugas pribadi belum selesai hari-hari sebelumnya',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Penyelesaian catatan pertanyaan setiap bagian kerja & kontrol buku masing-masing',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Cek stok error',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Kirim lamaran masuk ke atasan (setiap kali ada chat masuk)',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Follow up stock minus / bermasalah',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Kontrol centang tugas perhari dan semua tugas yang sudah selesai',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Jika tidak selesai (lebih dari 3 hari) pindahkan ke halaman berikutnya',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Absesi izin jam siang',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Penyelesaian kendala / permasalahan orang kerja / sistem',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Wajib dicatat setiap penyampaian baik tugas maupun bukan',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala atau apa yang belum terselesaikan & dan follow up tugas yang tidak terselesaikan ke atasan (pagi, siang, sore)',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Follow up balance kas, tugas harian, tugas pertanggal setiap bagian kerja dan pertanyaan yang belum selesai (senin-sabtu)',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Input barang masuk dan barang keluar yang sudah di tanda tangani boss',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Kontrol barang masuk dan barang keluar',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Cek tf kas, kas masuk, dan kas keluarm serta kode perkiraan jangan sampai salah',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Kontrol semua laporan, tidak boleh ada yang tidak isi',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],

            // Tugas untuk hari selasa
            [
                'title' => 'Penyelesaian catatan pertanyaan setiap bagian kerja (kontrol)',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Kontrol tugas harian dan pertanggal setiap bagian kerja ( kontrol buku tugas harian )',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Audit stok',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Cek tugas belum selesai, hari-hari sebelumnya (pagi-sore)',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Audit data bagian admin sale',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Check stock error',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Kirim lamaran masuk ke atasan (setiap kali ada chat masuk)',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Follow up stock minus / bermasalah',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Stock eror paket, follow up kak sheily',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Centang buku satu persatu tugas yang sudah selesai dikerjakan (semua bagian kerja)',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Centang keseluruhan tugas kerja yang sudah selesai dikerjakan (semua bagian kerja jika sudah 3 hari pindah ke depan)',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Follow up balance kas, tugas harian, tugas pertanggal setiap bagian dan pertanyaan yang belum seleesai',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Wajib dicatat setiap penyampaian tugas maupun bukan',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala atau apa yang belum terselesaikan & follow-up tugas yang tidak terselesaikan ke atasan (pagi, siang, sore)',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Input barang masuk dan keluar yang sudah ditanda tangani boss',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Kontrol barang masuk dan barang keluar',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Cek tf kas, kas masuk, kas keluar, serta kode perkiraan jangan sampai salah',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Kontrol semua laporan tidak boleh ada yang tidak di isi',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],

            // Tugas untuk hari rabu
            [
                'title' => 'Penyelesaian catatan pertanyaan setiap bagian kerja (kontrol)',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Kontrol tugas harian dan pertanggal setiap bagian kerja (kontrol buku harian tugas)',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Audit stok',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Cek tugas belum selesai, hari-hari sebelumnya (pagi-sore)',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Audit data bagian admin sale',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Check stock eror di komputer',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Kirim lamaran masuk ke atasn (setiap kali ada chat masuk)',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Follow up stock minus / bermasalah',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Stock error paket, follow up kak shelly',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Centang buku satu persatu tugas yang sudah selesai dikerjakan (semua bagian kerja)',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Centang keseluruhan tugas kerja yang sudah selesai dikerjakan (semua bagian kerja sudah 3 hari pindah kedepan)',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Follow up balance kas, tugas harian, tugas pertanggal setiap bagian dan pertanyaan yang belum selesai',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Wajib dicatat setiap setiap penyampaian tugas maupun bukan',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala atau apa yang belum terselesaikan & follow up tugas yang tidak terselesaikan ke atasan(pagi, siang, sore)',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Input barang masuk dan barang keluar yang sudah di tandatangani boss',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Kontrol barang masuk dan barang keluar',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Cek tf kas, kas masuk, kas keluar, serta kode perkiraan jangan sampai salah',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Kontrol semua laporan tidak boleh ada yang tidak di isi',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],

            // Tugas untuk hari kamis
            [
                'title' => 'Penyelesaian catatan pertanyaan setiap bagian kerja (kontrol)',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Kontrol tugas harian dan pertanggal setiap bagian kerja (kontrol buku tugas harian)',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Audit stok',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Cek tugas belum selesai, hari-hari sebelumnya (pagi-sore)',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Audit data bagian admin sale',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Cek stok error',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Kirim lamaran masuk ke atasan (setiap kali ada chat masuk)',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Follow up stock minus / bermasalah',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Stock error paket, follow up kak shelly',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Centang buku satu persatu tugas yang sudah selesai dikerjakan (semua bagian kerja)',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Jika tidak selesai (lebih dari 3 hari) pindahkan ke halaman berikutnya',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Absesi izin jam siang',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Penyelesaian kendala / permasalahan orang kerja / sistem',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Wajib dicatat setiap penyampaian baik tugas maupun bukan',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala atau apa yang belum terselesaikan & dan follow up tugas yang tidak terselesaikan ke atasan (pagi, siang, sore)',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Followup balance kas, tugas harian, tugas pertanggal setiap bagian kerja dan pertanyaan yang belum selesai (senin-sabtu)',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Input barang masuk dan barang keluar yang sudah di tanda tangani boss',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Kontrol barang masuk dan barang keluar',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Cek tf kas, kas masuk, dan kas keluarm serta kode perkiraan jangan sampai salah',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Kontrol semua laporan, tidak boleh ada yang tidak isi',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],

            // Tugas untuk hari jumat
            [
                'title' => 'Penyelesaian catatan pertanyaan setiap bagian kerja (kontrol)',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Kontrol tugas harian dan pertanggal setiap bagian kerja (kontrol buku tugas harian)',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Audit stok',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Cek tugas belum selesai, hari-hari sebelumnya (pagi-sore)',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Audit data bagian admin sale',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Check stock error',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Kirim lamaran masuk ke atasan (setiap kali ada chat masuk)',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Follow up stock minus / bermasalah',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Stock error paket, follow up kak sheily',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Centang buku satu persatu tuga yang sudah selesai dikerjakan (semua bagian kerja)',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Centang keseluruhan tugas kerja yang sudah selesai dikerjakan (semua bagian kerja jika sudah 3 hari pindah ke depan)',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Follow up balance kas, tugas harian, tugas pertanggal setiap bagian dan pertanyaan yang belum selesai',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Wajib dicatat setiap penyampaian tugas maupun bukan',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala atau apa yang belum terselesaika & follow up tugas yang tidak terselesaikan ke atasan (pagi, siang, sore)',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Input barang masuk dan barang keluar yang sudah ditanda tangani boss',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Kontrol barang masuk dan barang keluar',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Cek tf kas, kas masuk, kas keluar, serta kode perkiraan jangan sampai salah',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Cek kode perkiraan',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Kontrol semua laporan tidak boleh ada yang tidak diisi',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],

            // Tugas untuk hari sabtu
            [
                'title' => 'Penyelesaian catatan pertanyaan setiap bagian kerja (kontrol)',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Kontrol tugas harian dan pertanggal setiap bagian kerja (kontrol buku tugas harian)',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Audit stok',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Cek tugas belum selesai, hari-hari sebelumnya (pagi-sore)',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Audit data bagian admin sale  (kontrol pembayaran piutang online & offline)',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Check stock error',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Kirim lamaran masuk ke atasan (setiap kali ada chat masuk)',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Follow up stock minus / bermasalah',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Stock error paket, follow up kak sheily',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Centang buku satu persatu tuga yang sudah selesai dikerjakan (semua bagian kerja)',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Centang keseluruhan tugas kerja yang sudah selesai dikerjakan (semua bagian kerja jika sudah 3 hari pindah ke depan)',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Follow up balance kas, tugas harian, tugas pertanggal setiap bagian dan pertanyaan yang belum selesai',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Wajib dicatat setiap penyampaian tugas maupun bukan',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala atau apa yang belum terselesaika & follow up tugas yang tidak terselesaikan ke atasan (pagi, siang, sore)',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Input barang masuk dan barang keluar yang sudah ditanda tangani boss',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Kontrol barang masuk dan barang keluar',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Cek tf kas, kas masuk, kas keluar, serta kode perkiraan jangan sampai salah',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Cek kode perkiraan',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
            [
                'title' => 'Kontrol semua laporan tidak boleh ada yang tidak diisi',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role' => 'Manajemen',
                'show_on_dates' => null,
            ],
        ];


        // Insert the tasks into the database
        DB::table('tasks')->insert($tasks);
    }
}