<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TaskKepalaTokoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $taskkepalatoko = [];
        $taskkepalatoko = [
            // Tugas hari senin
            [
                'title' => 'Penyelesaian complain & saran',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol tugas harian & pertanggal setiap toko',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Penyelesaian tugas pertanyaan / lainnya belum selesai hari-hari sebelumnya (pagi-sore) dan wajib di catat setiap penyampaian tugas maupun bukan',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol tugas harian setiap toko',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Follow up barang kosong / barang baru ke pembelian',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Meeting dengan manajer (estimasi senin pagi)',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol ekspor dan impor data toko (sebelum jam 08:00)',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Fokuskan penjulan ke benih yang hampir mencapai expired',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Mencari konsumen baru',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala / lainnya yang belum terselesaikan dan follow up tugas yang tidak terselesaikan ke atasan',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol tugas data konsumen di toko / kebun setiap sore',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol stok toko',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol online via wa',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Cek yang harus di follow up dibuku / yang belum ada penyelesaian & wajib di catat  setiap penyampain tugas maupun bukan',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol cctv',
                'day' => 'Monday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],

            // Tugas hari Selasa
            [
                'title' => 'Penyelesaian complain & saran',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol tugas harian & pertanggal setiap toko',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Penyelesaian tugas pertanyaan / lainnya belum selesai hari-hari sebelumnya (pagi-sore) dan wajib di catat setiap penyampaian tugas maupun bukan',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol tugas harian setiap toko',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Follow up barang kosong / barang baru ke pembelian',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Meeting dengan manajer (estimasi senin pagi)',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol ekspor dan impor data toko (sebelum jam 08:00)',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Fokuskan penjulan ke benih yang hampir mencapai expired',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Mencari konsumen baru',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala / lainnya yang belum terselesaikan dan follow up tugas yang tidak terselesaikan ke atasan',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol toko (setiap selasa)',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Perhatikan produk yang layak & tidak layak dijual',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Benih exp (setiap 6-8 bulan) konfirmasi gudang',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Setiap hari selasa turun toko cek benih exp yang 6-8 bulan tukar ke gudang konfirmasi dengan Bang Ali, antar kembali benih tiap kamis, titip ke zul',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol stok toko',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Bawa uang pecahan untuk di toko-toko',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol online (via wa)',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol offline (turun langsung ke toko-toko)',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Control cctv',
                'day' => 'Tuesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],

            // Tugas hari Rabu
            [
                'title' => 'Penyelesaian complain & saran',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol tugas harian & pertanggal setiap toko',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Penyelesaian tugas pertanyaan / lainnya belum selesai hari-hari sebelumnya (pagi-sore) dan wajib di catat setiap penyampaian tugas maupun bukan',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol tugas harian setiap toko',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Follow up barang kosong / barang baru ke pembelian',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Meeting dengan manajer (estimasi senin pagi)',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol ekspor dan impor data toko (sebelum jam 08:00)',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Fokuskan penjulan ke benih yang hampir mencapai expired',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Mencari konsumen baru',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala / lainnya yang belum terselesaikan dan follow up tugas yang tidak terselesaikan ke atasan',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol stok toko',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol online (via wa)',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Control cctv',
                'day' => 'Wednesday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],

            // Tugas hari Kamis
            [
                'title' => 'Kontrol lapangan',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Penyelesaian complain & saran',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol tugas harian & pertanggal setiap toko',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Penyelesaian tugas pertanyaan / lainnya belum selesai hari-hari sebelumnya (pagi-sore) dan wajib di catat setiap penyampaian tugas maupun bukan',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol tugas harian setiap toko',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Follow up barang kosong / barang baru ke pembelian',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Meeting dengan manajer (estimasi senin pagi)',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol ekspor dan impor data toko (sebelum jam 08:00)',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Fokuskan penjulan ke benih yang hampir mencapai expired',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Mencari konsumen baru',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala / lainnya yang belum terselesaikan dan follow up tugas yang tidak terselesaikan ke atasan',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol stok toko',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol online (via wa)',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Cek yang harus di follow up di buku / yang belum ada penyelesaian & wajib di catat setiap penyampaian tugas maupun bukan',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Control cctv',
                'day' => 'Thursday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],

            // Tugas hari Jumat
            [
                'title' => 'Penyelesaian complain & saran',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol tugas harian & pertanggal setiap toko',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Penyelesaian tugas pertanyaan / lainnya belum selesai hari-hari sebelumnya (pagi-sore) dan wajib di catat setiap penyampaian tugas maupun bukan',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol tugas harian setiap toko',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Follow up barang kosong / barang baru ke pembelian',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol ekspor dan impor data toko (sebelum jam 08:00)',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Fokuskan penjulan ke benih yang hampir mencapai expired',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Mencari konsumen baru',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala / lainnya yang belum terselesaikan dan follow up tugas yang tidak terselesaikan ke atasan',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol stok toko',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol online (via wa)',
                'day' => 'Friday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],

            // Tugas hari Sabtu
            [
                'title' => 'Penyelesaian complain & saran',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol tugas harian & pertanggal setiap toko',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Penyelesaian tugas pertanyaan / lainnya belum selesai hari-hari sebelumnya (pagi-sore) dan wajib di catat setiap penyampaian tugas maupun bukan',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol tugas harian setiap toko',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Follow up barang kosong / barang baru ke pembelian',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol ekspor dan impor data toko (sebelum jam 08:00)',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Fokuskan penjulan ke benih yang hampir mencapai expired',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Mencari konsumen baru',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Konsultasi dengan atasan bila ada kendala / lainnya yang belum terselesaikan dan follow up tugas yang tidak terselesaikan ke atasan',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol stok toko',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
            [
                'title' => 'Kontrol online (via wa)',
                'day' => 'Saturday',
                'time' => '08:00:00',
                'completed' => false,
                'from_system' => true,
                'role'  => 'Kepala Toko',
            ],
        ];

        // Insert the tasks into the database
        DB::table('tasks')->insert($taskkepalatoko);
    }
}
